### PR TITLE
Add copyright to license

### PR DESCRIPTION
**Pull request by brimworks**

### CODE REVIEW

**Comment by ai** [comment]
1. `(C)` is a mark for “Copyright”. So here we have “Copyright Copyright”. I think we can keep `Copyright 2020 Ben Briggs`.
2. Can you do a little research to find how does Creative Commons recommend to put the name?
3. We need to put a year of creation (or the last human changes).

**Comment by brimworks** [comment]
Sorry @ai , but I am not a lawyer. That said, we are working with a lawyer to make sure we are complying with software licensing law and one of the requests was to ensure copyrights are shipped with our product.

Regarding (1), based on prior art, I think either way works just fine. Regarding (2) the closest thing from some internet search is this: https://creativecommons.org/use-remix/attribution/ from a "consuming the software you write" perspective, it would be easiest if this attribution was directly in the license file so that one can use `yarn licenses generate-disclaimer` to obtain this information. I'm not sure if (3) is a requirement, for example just adding this copyright is a change, right?

**Comment by ai** [comment]
> I am not a lawyer. That said, we are working with a lawyer to make sure we are complying with software licensing law and one of the requests was to ensure copyrights are shipped with our product.

Can you ask lawyer about what year and what names should be this header?

**Comment by ben-eb** [comment]
I am happy to relicense the _code_ under MIT but not the project as a whole. @ai's plan for GitHub Actions and splitting this repository into two parts seems like the way forward to me. https://github.com/browserslist/browserslist/issues/432

See also prior discussion;

* https://github.com/ben-eb/caniuse-lite/issues/40
* https://github.com/ben-eb/caniuse-lite/issues/14

**Pull request closed without merging**
