### PR TITLE
upgrade to babel7

### PR DESCRIPTION
**Pull request by sunny775**
The changes proposed by this PR will port the project to babel7.
This is quite needful, especially to other packages that depend on this module.
For instance, at Debian we currently maintain these changes as patches in the [Debian Package](https://salsa.debian.org/js-team/node-caniuse-lite) of caniuse-lite

### CODE REVIEW

**Comment by ai** [comment]
Do we need Babel at all.

We use it just in database generator.

**Comment by sunny775** [comment]
@ai if you can do away with Babel, that will even be better. Thanks a lot :)

**Comment by ai** [comment]
Fixed. We are now using Babel only to `data/` generation and I updated to Babel 7.

**Comment by sunny775** [comment]
Thanks @ai

**Pull request closed without merging**
